### PR TITLE
add option to customize the browser

### PR DESCRIPTION
**Pull request by bb2020**
Added ability to customize the browse function. For example eww can be used to make searches

### CODE REVIEW

**Comment by Malabarba** [comment]
Thanks for this. Could you just change the name to `google-this-browse-url-function`, and the docstring to:

      "Function used to browse urls.
    Possible values include: `browse-url', `browse-url-generic',
    `browse-url-emacs', `eww-browse-url'."

**Comment by bb2020** [comment]
Done

**Comment by Malabarba** [comment]
Awesome. Thanks again!

**Comment by bb2020** [comment]
Thanks for consideration

**Pull request merged**
